name: leaflet-gpx-heatmap
version: '0.1.0.0'
synopsis: TODO
maintainer: Tomáš Janoušek <tomi@nomi.cz>
copyright: (c) 2019 Tomáš Janoušek
license: BSD3
github: liskin/leaflet-gpx-heatmap

executable:
    source-dirs: src
    main: Main.hs
    dependencies:
        - ascii-progress
        - base
        - bytestring
        - bytestring-lexing
        - containers
        - deepseq
        - directory
        - filepath
        - parallel-io
        - vector
        - xeno
        - zlib
    ghc-options:
        - -Wall
        - -threaded
        - -with-rtsopts=-N
